import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { pack, type Item } from '../../src/core/model.js';

// Arbitrary for a single Item field set (id assigned separately to guarantee
// uniqueness). Priorities are finite integers (no NaN/Infinity) because
// compareItems relies on numeric subtraction. Tokens are non-negative integers.
const priorityArb = fc.integer({ min: -1000, max: 1000 });
const tokensArb = fc.nat({ max: 1000 });
const budgetArb = fc.nat({ max: 5000 });

/**
 * Generate an `Item[]` with unique ids. Uniqueness is achieved by generating a
 * set of distinct id strings, then zipping each with a randomly generated
 * priority/tokens pair.
 */
const itemsArb: fc.Arbitrary<Item[]> = fc
  .uniqueArray(fc.string({ minLength: 1, maxLength: 8 }), {
    minLength: 0,
    maxLength: 20,
  })
  .chain((ids) =>
    fc.tuple(
      ...ids.map((id) =>
        fc.record({
          id: fc.constant(id),
          priority: priorityArb,
          tokens: tokensArb,
        }),
      ),
    ),
  );

const totalTokens = (items: Item[]): number =>
  items.reduce((sum, i) => sum + i.tokens, 0);

const idSet = (items: Item[]): Set<string> => new Set(items.map((i) => i.id));

describe('pack — correctness properties', () => {
  // Property 1 — Budget: selected tokens never exceed the budget.
  // Validates: Requirements 1.1, 1.2, 1.3
  it('Property 1 — selected tokens never exceed the budget', () => {
    fc.assert(
      fc.property(itemsArb, budgetArb, (items, budget) => {
        const { selected, totalTokens: reported } = pack(items, budget);
        expect(totalTokens(selected)).toBeLessThanOrEqual(budget);
        // The reported total agrees with the summed selection.
        expect(reported).toBe(totalTokens(selected));
      }),
    );
  });

  // Property 2 — No priority inversion: min priority of selected >= max priority
  // of unselected. Vacuously true when either set is empty.
  // Validates: Requirements 1.1, 1.3, 2.2, 2.3
  it('Property 2 — no priority inversion between selected and unselected', () => {
    fc.assert(
      fc.property(itemsArb, budgetArb, (items, budget) => {
        const { selected } = pack(items, budget);
        const selectedIds = idSet(selected);
        const unselected = items.filter((i) => !selectedIds.has(i.id));

        if (selected.length === 0 || unselected.length === 0) {
          return; // vacuously true
        }

        const minSelected = Math.min(...selected.map((i) => i.priority));
        const maxUnselected = Math.max(...unselected.map((i) => i.priority));
        expect(minSelected).toBeGreaterThanOrEqual(maxUnselected);
      }),
    );
  });

  // Property 3 — Budget monotonicity: for b1 <= b2, selected(items, b1) is a
  // subset of selected(items, b2).
  // Validates: Requirements 1.3
  it('Property 3 — budget monotonicity (b1 <= b2 => selected subset)', () => {
    fc.assert(
      fc.property(itemsArb, budgetArb, budgetArb, (items, ba, bb) => {
        const b1 = Math.min(ba, bb);
        const b2 = Math.max(ba, bb);
        const selected1 = idSet(pack(items, b1).selected);
        const selected2 = idSet(pack(items, b2).selected);
        for (const id of selected1) {
          expect(selected2.has(id)).toBe(true);
        }
      }),
    );
  });

  // Property 4 — Order independence: shuffled input yields the same result.
  // The permutation is itself generated by fast-check via a shuffled copy of
  // the same items, so both `pack` calls receive identical multisets of items.
  // Validates: Requirements 2.1, 2.2, 2.3, 2.4
  it('Property 4 — order independence (shuffled input yields same result)', () => {
    fc.assert(
      fc.property(
        itemsArb.chain((items) =>
          fc.tuple(
            fc.constant(items),
            fc.shuffledSubarray(items, {
              minLength: items.length,
              maxLength: items.length,
            }),
          ),
        ),
        budgetArb,
        ([items, shuffled], budget) => {
          const base = pack(items, budget);
          const permuted = pack(shuffled, budget);

          expect(permuted.selected.map((i) => i.id)).toEqual(
            base.selected.map((i) => i.id),
          );
          expect(permuted.totalTokens).toBe(base.totalTokens);
        },
      ),
    );
  });
});
